id 1
type "admin"
email "adminx@me.com"
customer_id "MHalee34"
account_number "0001001901229114"
customer_category "Personal"
title "Eum doloremque et ad"
middle_name "Vaughan Zamora"
firstname "Halee"
lastname "Mosley"
dob "Lorem ut perferendis"
idcard "Nesciunt aliquip vo"
country "Velit et velit est"
city "Sint veniam ut maio"
mobile "Irure qui delectus"
street "Est ex aut rem sed l"
transfer_count "100"
transfer_status "Your transaction was not\ncomplete please contact your account\nofficer or send us an email:\nsupport@almenastatefinance.com\nto resolve transfer issue."
preferred_name "Damian Hurst"
preferred_city "Officia dolore tempo"
email_verified_at null
status "Free"
created_at "2022-10-07T20:05:22.000000Z"
updated_at "2022-10-07T20:05:22.000000Z"